### ISSUE TITLE
ApproxFun support

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/DomainSets.jl#5]
- [X] Get ApproxFun to compile using Domains.jl
- [ ] Move any "general purpose" domains over (`Arc`, `UnionDomain`) 
- [x] Delete redundant domains in ApproxFun
- [ ] #1 Support complex domains
- [x] #2 
- [ ] #3  Support derivatives of maps
- [x] #4  Publish to METADATA
- [x] #6

I'm considering moving ApproxFun over now: the only scalable way to do https://github.com/JuliaApproximation/ApproxFun.jl/issues/531 I can see is by adding support for `Chebyhev(ChebyshevInterval())`, which returns points `ChebyshevGrid(n)`, while `Chebyshev(Interval(a,b))` has points `MappedGrid(ChebyshevGrid(n), AffineMap(...))`.  This change to `ChebyshevInterval` would also simplify a lot of the code.

**Comment by daanhb** [comment]
I'm up for a round of development to make the integration happen. I've just added you as collaborator.

**Comment by dlfivefifty** [comment]
This is a bit annoying: in the latest branches
```julia
a = Chebyshev(ChebyshevInterval());   b = Ultraspherical(1, domain(a))
precompile(union, (a,b))
```
throws a SEGFAULT.

We may have to postpone to v0.7.

**Comment by dlfivefifty** [comment]
https://github.com/JuliaLang/julia/issues/23792
